### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by rokusottervanger** [tue-robotics/tue_manipulation#1]
In file included from /usr/include/eigen3/Eigen/Core:277:0,
                 from /opt/ros/hydro/include/kdl/jacobian.hpp:26,
                 from /opt/ros/hydro/include/kdl/jntarray.hpp:26,
                 from /home/rokus/ros/hydro/system/src/tue_manipulation/include/tue/manipulation/ik_solver.h:6,
                 from /home/rokus/ros/hydro/system/src/tue_manipulation/src/grasp_precompute_action.cpp:14:
/usr/include/eigen3/Eigen/src/Core/DenseBase.h: In instantiation of ‘class Eigen::DenseBase<Eigen::Matrix<double, 6, -1> >’:
/usr/include/eigen3/Eigen/src/Core/MatrixBase.h:61:34:   required from ‘class Eigen::MatrixBase<Eigen::Matrix<double, 6, -1> >’
/usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:65:7:   required from ‘class Eigen::PlainObjectBase<Eigen::Matrix<double, 6, -1> >’
/usr/include/eigen3/Eigen/src/Core/Matrix.h:140:7:   required from ‘class Eigen::Matrix<double, 6, -1>’
/opt/ros/hydro/include/kdl/jacobian.hpp:40:48:   required from here
/usr/include/eigen3/Eigen/src/Core/DenseBase.h:103:10: warning: enumeral mismatch in conditional expression: ‘Eigen::internal::size_at_compile_time<6, -1>::<anonymous enum>’ vs ‘Eigen::internal::traits<Eigen::Matrix<double, 6, -1> >::<anonymous enum>’ [-Wenum-compare]
/usr/include/eigen3/Eigen/src/Core/DenseBase.h: In instantiation of ‘class Eigen::DenseBase<Eigen::Matrix<double, -1, 1> >’:
/usr/include/eigen3/Eigen/src/Core/MatrixBase.h:61:34:   required from ‘class Eigen::MatrixBase<Eigen::Matrix<double, -1, 1> >’
/usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:65:7:   required from ‘class Eigen::PlainObjectBase<Eigen::Matrix<double, -1, 1> >’
/usr/include/eigen3/Eigen/src/Core/Matrix.h:140:7:   required from ‘class Eigen::Matrix<double, -1, 1>’
/opt/ros/hydro/include/kdl/jntarray.hpp:72:25:   required from here
/usr/include/eigen3/Eigen/src/Core/DenseBase.h:103:10: warning: enumeral mismatch in conditional expression: ‘Eigen::internal::size_at_compile_time<-1, 1>::<anonymous enum>’ vs ‘Eigen::internal::traits<Eigen::Matrix<double, -1, 1> >::<anonymous enum>’ [-Wenum-compare]
/home/rokus/ros/hydro/system/src/tue_manipulation/src/grasp_precompute_action.cpp: In function ‘int main(int, char*_)’:
/home/rokus/ros/hydro/system/src/tue_manipulation/src/grasp_precompute_action.cpp:439:52: error: no matching function for call to ‘ros::NodeHandle::param(std::string&, const char [1])’
/home/rokus/ros/hydro/system/src/tue_manipulation/src/grasp_precompute_action.cpp:439:52: note: candidate is:
In file included from /opt/ros/hydro/include/ros/ros.h:45:0,
                 from /home/rokus/ros/hydro/system/src/tue_manipulation/src/grasp_precompute_action.cpp:4:
/opt/ros/hydro/include/ros/node_handle.h:1912:8: note: template<class T> void ros::NodeHandle::param(const string&, T&, const T&) const
/opt/ros/hydro/include/ros/node_handle.h:1912:8: note:   template argument deduction/substitution failed:
/home/rokus/ros/hydro/system/src/tue_manipulation/src/grasp_precompute_action.cpp:439:52: note:   cannot convert ‘""’ (type ‘const char [1]’) to type ‘std::basic_string<char>&’
make[2]: *_\* [tue_manipulation/CMakeFiles/grasp_precompute_action.dir/src/grasp_precompute_action.cpp.o] Error 1
make[1]: **\* [tue_manipulation/CMakeFiles/grasp_precompute_action.dir/all] Error 2
make: **\* [all] Error 2
Invoking "make" failed

**Comment by Timple** [comment]
Joh, I thought we migrated to Indigo already ;-)

Looks like I messed up strings and chars somewhere (stupid syntax). I'll look into it on tuesday

**Comment by rokusottervanger** [comment]
It's in 339a7dfa43090605a1b3e3c994344a55d82dc74e. The param() call is wrong. Just add the name of the param you are querying as a first argument. I could do that, to fix the build error, but I don't know exactly what you wanted to do with that commit...

**Comment by Timple** [comment]
Strange that is worked in my code. 
But I was getting rid of the whole tf_prefix thing. I read the code as strings being added but it seems like I overlooked the comma.

I would suggest something like this, but I have no ability to test:

// ToDo: make nice
    ~~nh_private.paramstd::string(EXT_ROOT_LINK, "");~~
    ~~TIP_LINK = EXT_ROOT_LINK+"/"+TIP_LINK;~~
    EXT_ROOT_LINK = ROOT_LINK;

**Comment by Timple** [comment]
If that works of course we can replace EXT_ROOT_LINK by ROOT_LINK in the whole file/package

**Comment by rokusottervanger** [comment]
How do I test if that works at runtime?

**Comment by Timple** [comment]
roscore
astart
amiddle
amigo-console -> amigo.leftArm.send_goal(0.5,0.2,0.8,0,0,0,pre_grasp=True)

**Comment by Timple** [comment]
:thumbsup:
