### ISSUE TITLE
Build error regarding OpenCV

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_manipulation#20]
Errors     << tue_manipulation:make /home/amigo/ros/kinetic/system/logs/tue_manipulation/build.make.054.log       
/home/amigo/ros/kinetic/system/devel/.private/tue_manipulation/lib/libtue_manipulation.so: undefined reference to `cv::waitKey(int)'
/home/amigo/ros/kinetic/system/devel/.private/tue_manipulation/lib/libtue_manipulation.so: undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/amigo/ros/kinetic/system/devel/.private/tue_manipulation/lib/tue_manipulation/test_robot_ik] Error 1
make[1]: *** [CMakeFiles/test_robot_ik.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/amigo/ros/kinetic/system/devel/.private/tue_manipulation/lib/libtue_manipulation.so: undefined reference to `cv::waitKey(int)'
/home/amigo/ros/kinetic/system/devel/.private/tue_manipulation/lib/libtue_manipulation.so: undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/amigo/ros/kinetic/system/devel/.private/tue_manipulation/lib/tue_manipulation/test_multi_refgen] Error 1
make[1]: *** [CMakeFiles/test_multi_refgen.dir/all] Error 2

**Comment by rokusottervanger** [comment]
@reinzor You worked on this with Sjoerd. Can we remove the graph viewer that introduces the OpenCV dependency?

**Comment by reinzor** [comment]
IMO not really priority, better to just let it sit there

-Rein

On Tue, Dec 19, 2017 at 9:51 PM, Rokus Ottervanger <notifications@github.com
