### ISSUE TITLE
Crash on middleware startup

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/tue_manipulation#7]
[ERROR] [1486571980.512626702]: Failed to fetch current robot state
[ERROR] [1486571980.513612045]: Failed to fetch current robot state
[amigo/grasp_precompute_left_arm-3] process has died [pid 18047, exit code -11, cmd /home/rein/ros/kinetic/dev/devel/lib/tue_manipulation/grasp_precompute_action joint_trajectory_action:=left_arm/joint_trajectory_action joint_trajectory:=left_arm/joint_trajectory grasp_precompute:=left_arm/grasp_precompute ik_position_markers:=left_arm/ik_position_markers joint_measurements:=left_arm/measurements spindle_measurement:=torso/measurements __name:=grasp_precompute_left_arm __log:=/home/rein/.ros/log/15c9fabe-ee1d-11e6-8abf-a0a8cd88ac07/amigo-grasp_precompute_left_arm-3.log].
log file: /home/rein/.ros/log/15c9fabe-ee1d-11e6-8abf-a0a8cd88ac07/amigo-grasp_precompute_left_arm-3*.log
[amigo/grasp_precompute_right_arm-5] process has died [pid 18065, exit code -11, cmd /home/rein/ros/kinetic/dev/devel/lib/tue_manipulation/grasp_precompute_action joint_trajectory_action:=right_arm/joint_trajectory_action joint_trajectory:=right_arm/joint_trajectory grasp_precompute:=right_arm/grasp_precompute ik_position_markers:=right_arm/ik_position_markers joint_measurements:=right_arm/measurements spindle_measurement:=torso/measurements __name:=grasp_precompute_right_arm __log:=/home/rein/.ros/log/15c9fabe-ee1d-11e6-8abf-a0a8cd88ac07/amigo-grasp_precompute_right_arm-5.log].
log file: /home/rein/.ros/log/15c9fabe-ee1d-11e6-8abf-a0a8cd88ac07/amigo-grasp_precompute_right_arm-5*.log

**Comment by reinzor** [comment]
This is now also present on the real robot @jlunenburg , PR https://github.com/tue-robotics/tue_manipulation/pull/8 fixed the segfault but the robot hangs now in the "cannot get robot_state" loop. This is due to a update of a third party library, I think `MoveIt`. 

https://discourse.ros.org/t/new-packages-in-kinetic-2017-02-17/1348

This explains why it was only present at my laptop since it was configured to use the http://wiki.ros.org/ShadowRepository . 

This issue has high prio since manipulation is not working anymore.

**Comment by jlunenburg** [comment]
I'll have a look ASAP

**Comment by jlunenburg** [comment]
Fixed by 97dba8b00627ff995c098c59b04ed5be05662c95
